In [1]:
import torch

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# Vector
# Pytorch accepts only the values with same data types and if the data types are different then it convets all into one dtypes as below
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# Matrix
# Matrix in Pytorch should be of same length for all the rows and coloumns otherwise it throws an error of different length
t3 = torch.tensor([[5., 6],[7, 8],[9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [11]:
# 3D Matrix
t4 = torch.tensor([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9.],
                  [10,11,12]]])
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [7]:
t1.shape

torch.Size([])

In [8]:
t2.shape

torch.Size([4])

In [9]:
t3.shape

torch.Size([3, 2])

In [12]:
t4.shape

torch.Size([2, 2, 3])