In [2]:
import torch
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [3]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [5]:
# The above expression can also be written in this way as well but the only differenece between the both is "torch.from_numpy" does not creates a new memory
# where as "torch.tensor" creates a new memory in the space
y1 = torch.tensor(x)
y1

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [7]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)